apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{name}-envoy-gateway-tls"
  namespace: "{namespace}"
spec:
  dnsNames:
    "{dns_names}"
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: "{name}-envoy-gateway-tls"